data_root: ../cross_task_tool_neurons_data
raw_dataset_dir: ../cross_task_tool_neurons_data/datasets/raw_when2tool
modified_dataset_dir: ../cross_task_tool_neurons_data/datasets/modified_when2tool
labels_dir: ../cross_task_tool_neurons_data/labels
activations_dir: ../cross_task_tool_neurons_data/activations
neurons_dir: ../cross_task_tool_neurons_data/neurons
outputs_dir: ../cross_task_tool_neurons_data/outputs
visualizations_dir: ../cross_task_tool_neurons_data/visualizations
checkpoints_dir: ../cross_task_tool_neurons_data/checkpoints
causal_validation_dir: ../cross_task_tool_neurons_data/causal_validation
when2tool_repo: ../when2tool_repo
